# Generated by Django 5.1.6 on 2025-03-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('Group Stage', 'Group Stage'), ('Round of 256', 'Round of 256'), ('Round of 128', 'Round of 128'), ('Round of 64', 'Round of 64'), ('Round of 32', 'Round of 32'), ('Round of 16', 'Round of 16'), ('Quarterfinals', 'Quarterfinals'), ('Semifinals', 'Semifinals'), ('Finals', 'Finals')], max_length=50)),
                ('event_type', models.CharField(choices=[('Sabre', 'Sabre'), ('Foil', 'Foil'), ('Epee', 'Epee')], max_length=50)),
                ('match_date', models.DateTimeField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1_yellowcard', models.IntegerField()),
                ('player2_yellowcard', models.IntegerField()),
                ('player1_forfeit', models.BooleanField()),
                ('player2_forfeit', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
